// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyacwfzdaciskhlclrby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YWN3ZnpkYWNpc2tobGNscmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTEzODMsImV4cCI6MjA2OTk4NzM4M30.MzvPmZOeCh0l-Ggntr7zhHMMwc_DHW79wiyRyx2AHMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'aura-web-app',
    },
  },
});